// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateReply(ctx context.Context, arg CreateReplyParams) (Reply, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, id int64) error
	DeletePost(ctx context.Context, id int64) error
	DeleteReply(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetComment(ctx context.Context, id int64) (Comment, error)
	GetCommentForUpdate(ctx context.Context, id int64) (Comment, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetPostForUpdate(ctx context.Context, id int64) (Post, error)
	GetReply(ctx context.Context, id int64) (Reply, error)
	GetReplyForUpdate(ctx context.Context, id int64) (Reply, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserForUpdate(ctx context.Context, id int64) (User, error)
}

var _ Querier = (*Queries)(nil)
